### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by theralfbrown** [aurel26/s-4-u-for-windows#1]
compiled.and run successfully.but i run it under system privileged and non system privilege.both give me same following error ;
"LsaLogonUser failed (error 0xc000000d)"
its happen for you? whats the reason?
how can i solve it?

**Comment by aurel26** [comment]
What is the version of your Windows ?

**Comment by theralfbrown** [comment]
2008r2 (ver 6.1.76.0.1)

**Comment by aurel26** [comment]
With Windows 7 64bit edition (or Windows Server 2008 R2), there is a bug when LSASS converts buffers from a 32-bit process (only for MsV1_0S4ULogon messages).

The only solution is to call LSASS from a 64-bit process to avoid conversion. You must recompile s-4-u and choose 64-bit platform.

This bug was corrected in Windows 8 and Windows Server 2012.

**Comment by theralfbrown** [comment]
thanks.but i compiled it both 32 & 64 bit and test it on win7 64bit and 32bit and give me the same error.(standalone & domain were tested)

**Comment by m00dy-** [comment]
Happy to have s4u running (compiled using wdk toolchain) .
Thank you aurelien for the hint regarding the bug under windows 7 /Windows 2008r2

**Comment by aurel26** [comment]
Damned!

Is it the same error code?
Have you try with a standalone Windows 7 (non domain member)?

**Comment by lanjelot** [comment]
Thanks for the hint @aurel26, it works like a charm now. I've tested it successfully on Windows 7 x64 (standalone and domain joined), 2008 R2 x64 (promoted to DC) and 2012 R2 x64 (promoted to DC). Thanks heaps for publishing!

**Comment by JaromirDegtyarev** [comment]
big thanks for your try.i run s4u as system privilege by psexec.and show me the following error:
s4u domain.local\administrator
	AdjustTokenPrivileges (SeTcbPrivilege): OK
	LsaLogonUser failed (error 0xc000000d).
this test was on win7 x64 standalone and domain joined

**Comment by theralfbrown** [comment]
problem found.getting system privilege with psexec make this error.thank you.

**Comment by mubix** [comment]
Running from:
```
meterpreter > sysinfo
Computer        : TARGET_WIN7
OS              : Windows 7 (Build 7601, Service Pack 1).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/win64
meterpreter >
```

Running as:
```
meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
```

Running in:
```
meterpreter > getpid
Current pid: 456
meterpreter > ps -S 456


Process list
============

 PID   Name                    Arch  Session  User                          Path
 ---   ----                    ----  -------  ----                          ----
 456   wininit.exe             x64   0        NT AUTHORITY\SYSTEM           C:\Windows\system32\wininit.exe
```

Getting the same error mentioned above:
```
C:\temp>s4u .\Administrator
s4u .\Administrator
AdjustTokenPrivileges (SeTcbPrivilege): OK
LsaLogonUser failed (error 0xc000000d).
```

Compiled out of the box, with 2013 VS Community Edition on Release / X64

**Comment by aurel26** [comment]
0xc000000d was corrected with commit df8c1da0db29b4ce9a070fe36e5c07c1b7701223

**Comment by Flinkas** [comment]
Hi!
The token does not have the specified privilege (SeTcbPrivilege).

Any idea about how to bypass this?

Thanks.

**Comment by Flinkas** [comment]
How to get the correct privilege to run, since using PSexec will throw LsaLogonUser failed (error 0xc000000d) and from a Service we are not able to open interactive windows?
