### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rgl** [aurel26/s-4-u-for-windows#4]
Can you please apply an explicit license to this repo? You can do it from the GitHub [Insights / Community tab](https://github.com/aurel26/s-4-u-for-windows/community/license/new?branch=master).

MIT would be ideal :-)

BTW, I've added support for loading the user profile, environment variables, and [github actions workflow](https://github.com/rgl/s-4-u-for-windows/actions) (among other minor tweaks) at https://github.com/rgl/s-4-u-for-windows, let me known if you want a PR with it.

**Comment by aurel26** [comment]
I just committed a license to this repo. Yes, MIT seems suitable.

With pleasure for PR on this project which is a little outdated now.
